
services:

  mpiweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1101:8000  # port du server : port de l'application
    volumes:
      - .:/mpi-app/
    env_file:
      - ./.env
    restart: always
    depends_on:
      - mpiDB

  mpiDB:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 1102:8080
    networks:
      - mpi_default

networks:
  mpi_default:

volumes:
  pgdata:
    driver: local
  static_volume:
  media_volume: