openapi: 3.0.3
info:
  title: MPI API
  version: 1.0.0
  description: API centrale de communication inter-plateforme (patients, accès, token...)
paths:
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /mpipatients/:
    get:
      operationId: mpipatients_list
      tags:
      - mpipatients
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
          description: ''
    post:
      operationId: mpipatients_create
      tags:
      - mpipatients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Patient'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Patient'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
  /mpipatients/{id}/:
    get:
      operationId: mpipatients_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this patient.
        required: true
      tags:
      - mpipatients
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
    put:
      operationId: mpipatients_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this patient.
        required: true
      tags:
      - mpipatients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Patient'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Patient'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
    patch:
      operationId: mpipatients_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this patient.
        required: true
      tags:
      - mpipatients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPatient'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPatient'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPatient'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
    delete:
      operationId: mpipatients_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this patient.
        required: true
      tags:
      - mpipatients
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /mpipatients/{id}/track_platforms/:
    get:
      operationId: mpipatients_track_platforms_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this patient.
        required: true
      tags:
      - mpipatients
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
  /mpipatients/search/:
    get:
      operationId: mpipatients_search_retrieve
      tags:
      - mpipatients
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
  /mpipatients/sync/:
    post:
      operationId: mpipatients_sync_create
      tags:
      - mpipatients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Patient'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Patient'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
  /mpiplatforms/:
    get:
      operationId: mpiplatforms_list
      tags:
      - mpiplatforms
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Platform'
          description: ''
    post:
      operationId: mpiplatforms_create
      tags:
      - mpiplatforms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Platform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Platform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Platform'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
          description: ''
  /mpiplatforms/{id}/:
    get:
      operationId: mpiplatforms_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this platform.
        required: true
      tags:
      - mpiplatforms
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
          description: ''
    put:
      operationId: mpiplatforms_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this platform.
        required: true
      tags:
      - mpiplatforms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Platform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Platform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Platform'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
          description: ''
    patch:
      operationId: mpiplatforms_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this platform.
        required: true
      tags:
      - mpiplatforms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPlatform'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
          description: ''
    delete:
      operationId: mpiplatforms_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this platform.
        required: true
      tags:
      - mpiplatforms
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /mpiplatforms/{id}/toggle_access/:
    post:
      operationId: mpiplatforms_toggle_access_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this platform.
        required: true
      tags:
      - mpiplatforms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Platform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Platform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Platform'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
          description: ''
  /platform/token/:
    post:
      operationId: platform_token_create
      description: Permet aux plateformes d'obtenir un token JWT en utilisant leur
        `api_key` et `username`
      tags:
      - platform
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlatformAuth'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PlatformAuth'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PlatformAuth'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformAuth'
          description: ''
components:
  schemas:
    BlankEnum:
      enum:
      - ''
    GenreEnum:
      enum:
      - HOMME
      - FEMME
      type: string
      description: |-
        * `HOMME` - Homme
        * `FEMME` - Femme
    GroupeSanguinEnum:
      enum:
      - A+
      - O+
      - B+
      - AB+
      - A-
      - O-
      - B-
      - AB-
      type: string
      description: |-
        * `A+` - A+
        * `O+` - O+
        * `B+` - B+
        * `AB+` - AB+
        * `A-` - A-
        * `O-` - O-
        * `B-` - B-
        * `AB-` - AB-
    NullEnum:
      enum:
      - null
    PatchedPatient:
      type: object
      properties:
        upi:
          type: string
          format: uuid
          readOnly: true
        nom:
          type: string
          maxLength: 225
        prenoms:
          type: string
          maxLength: 225
        contact:
          type: string
          maxLength: 225
        adresse_mail:
          type: string
          format: email
          nullable: true
          maxLength: 50
        date_naissance:
          type: string
          format: date
        genre:
          $ref: '#/components/schemas/GenreEnum'
        nationalite:
          type: string
          nullable: true
          maxLength: 200
        ethnie:
          type: string
          nullable: true
          maxLength: 100
        profession:
          type: string
          nullable: true
          maxLength: 100
        employeur:
          type: string
          nullable: true
          maxLength: 100
        niveau_etude:
          type: string
          nullable: true
          maxLength: 100
        groupe_sanguin:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/GroupeSanguinEnum'
          - $ref: '#/components/schemas/BlankEnum'
          - $ref: '#/components/schemas/NullEnum'
        num_cmu:
          type: string
          nullable: true
          maxLength: 100
        cni_num:
          type: string
          nullable: true
          maxLength: 100
        cni_nni:
          type: string
          nullable: true
          maxLength: 100
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        qr_code:
          type: string
          format: uri
          nullable: true
        platforms_registered:
          type: array
          items:
            $ref: '#/components/schemas/Platform'
          readOnly: true
        platforms_accessed:
          type: array
          items:
            $ref: '#/components/schemas/Platform'
          readOnly: true
    PatchedPlatform:
      type: object
      description: Sérialiseur pour les plateformes connectées au MPI
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        api_key:
          type: string
          readOnly: true
        is_active:
          type: boolean
    Patient:
      type: object
      properties:
        upi:
          type: string
          format: uuid
          readOnly: true
        nom:
          type: string
          maxLength: 225
        prenoms:
          type: string
          maxLength: 225
        contact:
          type: string
          maxLength: 225
        adresse_mail:
          type: string
          format: email
          nullable: true
          maxLength: 50
        date_naissance:
          type: string
          format: date
        genre:
          $ref: '#/components/schemas/GenreEnum'
        nationalite:
          type: string
          nullable: true
          maxLength: 200
        ethnie:
          type: string
          nullable: true
          maxLength: 100
        profession:
          type: string
          nullable: true
          maxLength: 100
        employeur:
          type: string
          nullable: true
          maxLength: 100
        niveau_etude:
          type: string
          nullable: true
          maxLength: 100
        groupe_sanguin:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/GroupeSanguinEnum'
          - $ref: '#/components/schemas/BlankEnum'
          - $ref: '#/components/schemas/NullEnum'
        num_cmu:
          type: string
          nullable: true
          maxLength: 100
        cni_num:
          type: string
          nullable: true
          maxLength: 100
        cni_nni:
          type: string
          nullable: true
          maxLength: 100
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        qr_code:
          type: string
          format: uri
          nullable: true
        platforms_registered:
          type: array
          items:
            $ref: '#/components/schemas/Platform'
          readOnly: true
        platforms_accessed:
          type: array
          items:
            $ref: '#/components/schemas/Platform'
          readOnly: true
      required:
      - contact
      - created_at
      - date_naissance
      - genre
      - nom
      - platforms_accessed
      - platforms_registered
      - prenoms
      - updated_at
      - upi
    Platform:
      type: object
      description: Sérialiseur pour les plateformes connectées au MPI
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        api_key:
          type: string
          readOnly: true
        is_active:
          type: boolean
      required:
      - api_key
      - id
      - name
    PlatformAuth:
      type: object
      properties:
        username:
          type: string
        api_key:
          type: string
      required:
      - api_key
      - username
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    oauth2:
      type: oauth2
      flows: {}
