# Generated by Django 4.2.19 on 2025-02-14 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(db_index=True, max_length=225)),
                ('prenoms', models.CharField(db_index=True, max_length=225)),
                ('date_naissance', models.DateField(db_index=True)),
                ('contact', models.CharField(db_index=True, max_length=225)),
                ('adresse_mail', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('genre', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=10)),
                ('nationalite', models.CharField(max_length=200)),
                ('ethnie', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('employeur', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_etude', models.CharField(blank=True, max_length=100, null=True)),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+')], max_length=20, null=True)),
                ('num_cmu', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('platforms_accessed', models.ManyToManyField(blank=True, related_name='patients_accessed', to='patient.platform')),
                ('platforms_registered', models.ManyToManyField(blank=True, related_name='patients_registered', to='patient.platform')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('view_patient_name', 'Can view patient name'), ('view_dossier_patient', 'Can View dossier patient')),
            },
        ),
    ]
