# Generated by Django 4.2.19 on 2025-02-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationalite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
