# Generated by Django 4.2.19 on 2025-02-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_groupe_sanguin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cni_nni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_mere', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_pere', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PatientHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=225, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('employeur', models.CharField(blank=True, max_length=100, null=True)),
                ('situation_matrimoniale', models.CharField(blank=True, choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié'), ('Divorcé', 'Divorcé'), ('Veuf', 'Veuf')], max_length=50, null=True)),
                ('nbr_enfants', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('maladie_chronique', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='patient.patient')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
