# Generated by Django 4.2.19 on 2025-03-30 11:26

from django.db import migrations, models
import django.db.models.deletion
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_cni_num_patient_contact_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cni_nni',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cni_num',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='num_cmu',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='patienthistorique',
            name='adresse',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistorique',
            name='contact',
            field=models.CharField(blank=True, db_index=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistorique',
            name='employeur',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistorique',
            name='profession',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='api_key',
            field=models.CharField(default=patient.models.generate_api_key, editable=False, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PlatformAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.platform')),
            ],
        ),
    ]
