# Generated by Django 4.2.19 on 2025-03-30 18:14

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_platform_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='api_key',
            field=models.CharField(default=patient.models.generate_api_key, max_length=255, unique=True),
        ),
    ]
