# Generated by Django 4.2.19 on 2025-03-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_platform_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='genre',
            new_name='sexe',
        ),
    ]
