# Generated by Django 4.2.19 on 2025-03-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_rename_genre_patient_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='qr_code',
        ),
    ]
