# Generated by Django 4.2.19 on 2025-03-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_remove_patient_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
